### ISSUE TITLE
[suggestion] replace disqus with github

### ISSUE THREAD

**Issue by c33s** [TomasVotruba/tomasvotruba.com#1119]
i wanted to write a comment on your monorepo post but i don't have and don't want a disqus account. also i try to avoid allowing to much javascript. struggled around and thought that i will just open a ticket on your symplify/symplify repo and hope that you are ok with it. 

then i thought, it would be cool to use the github issues as commenting system. most of the developers visting a developers blog will have a github account. just googled for it and viola: https://pknopf.com/post/2018-10-13-comments-for-static-sites-using-github-issues/

i really love pauls solution as it requires no oauth and no javacscript on the client side.

fully understand if you stick to your solution but i wanted to share the idea and a possible solution. maybe you also want to get rid of the disqus dependency.

edit: 
https://jareddillard.com/blog/using-github-issues-for-static-blog-comments.html

**Comment by TomasVotruba** [comment]
Hi,

thanks for suggestion. 
My first impression: the context switching from website to GitHub is not way to go. Having information on 2 places will only go wrong.

**Comment by c33s** [comment]
what a pitty. i think commenting via github is a really awesome feature. no additionally account needed, no javascript requirement from a data collector (disqus). the informations are only on one place as github is the "only truth" but of course your blog your choice :)

not sure what is still relevant for disqus but a central instance where comments are stored can't be anything else than tracking. as we are tracked on github i see no reason for adding one additional tracker.

- https://www.infosecurity-magazine.com/news/disqus-breach-exposed-175m-emails/
- https://fatfrogmedia.com/delete-disqus-comments-wordpress/
- https://notes.ayushsharma.in/2017/09/im-killing-disqus-comments-on-my-blog-heres-why

**Comment by TomasVotruba** [comment]
I love Github and I'm 100 % for simplifying. 
Just scope jumping is one of the main attention and deep work killer.

When GitHub adds comments that would work as any other comments - under the content they comments to - we can give it try.
