### ISSUE TITLE
Are these bytes coming back? (broken link)

### ISSUE THREAD

**Issue by leonstafford** [TomasVotruba/tomasvotruba.com#1140]
https://tomasvotruba.com/cleaning-lady-checklist/

**Comment by TomasVotruba** [comment]
Thanks for report :+1: 

Should be working: https://github.com/TomasVotruba/tomasvotruba.com/blob/6cbc6692a1bed37657d100d1667509596290b328/packages/cleaning-lady/src/Controller/CleaningLadyCheckListController.php#L20

Probably missing in paths in `twig.php`

**Comment by leonstafford** [comment]
I found the neat `composer run-script check-status` command available and running that, but GH Pages seems to be responding with `429 Too Many requests` as it hits crawls/`HEAD` requests it pretty quickly. Even with partial crawl, looks like there's a few more internal/external URLs that may need attention:

```
Crawled 1092 url(s) with statuscode 200
Crawled 742 url(s) with statuscode 301
Crawled 98 url(s) with statuscode 302
Crawled 1 url(s) with statuscode 307
Crawled 3 url(s) with statuscode 308
Crawled 61 url(s) with statuscode 400
Crawled 2 url(s) with statuscode 403
Crawled 30 url(s) with statuscode 404
Crawled 3 url(s) with statuscode 410
Crawled 680 url(s) with statuscode 429
Crawled 1 url(s) with statuscode 500
```

**Comment by TomasVotruba** [comment]
I check website 2-3 times a year. Github token should help with requests.

The tool reports false positives for demo urls like, https://example.com, that I use in posts.
What is exact list of missing pages?
