### ISSUE TITLE
[post] these are my mistakes - deprecated post and what went wrong

### ISSUE THREAD

**Issue by TomasVotruba** [TomasVotruba/tomasvotruba.com#1202]
- on importance of admiting mistakes and reflect on the past
- it's ok to be passionate about something and share it, but if you find it not useful, you should tell people too
- avoid long tail spreading of knowledgeg you don't agree with anymore
- change your mind and change the wolrd https://www.huffpost.com/entry/change-your-mind-and-change-the-world_b_3325476
- inspired by chat with @matthiasnoback

**Comment by matthiasnoback** [comment]
Nice one!

**Comment by TomasVotruba** [comment]
This is pretty deprecated... hell yeah or no :D
