### ISSUE TITLE
[book] Monorepo in PHP - From Zero to Hero

### ISSUE THREAD

**Issue by TomasVotruba** [TomasVotruba/tomasvotruba.com#1236]
See https://github.com/TomasVotruba/book-monorepo-in-php-from-zero-to-hero

**Comment by TomasVotruba** [comment]
https://github.com/TomasVotruba/book-monorepo-in-php-from-zero-to-hero

**Comment by llaville** [comment]
Dead link!

**Comment by TomasVotruba** [comment]
Private for obvious purposes :)

**Comment by TomasVotruba** [comment]
Not enough traction to make a book about it
