### ISSUE TITLE
[issue] Using the dg/bypass-finals to mock final class has different results

### ISSUE THREAD

**Issue by peter279k** [TomasVotruba/tomasvotruba.com#1299]
As title, in [this blog post](https://tomasvotruba.com/blog/2019/03/28/how-to-mock-final-classes-in-phpunit), it seems that using the `dg/bypass-finals` with `bootstrap.php file` and `setUp() Method?` approaches have different results.

- When I use the `PHPUnit 9.5.20` with `bootstrap.php file` and `setUp()` approaches, they don't have the warnings about "Class "AnotherClass" is declared "final" and cannot be mocked." message.
- I guess latest PHPUnit 9 version will not get above warning message and I think the output message should be modified.

**Comment by TomasVotruba** [comment]
Thanks for sharing. What do recommend to change?

**Comment by peter279k** [comment]
Thanks for your reply. I create the PR to try to resolve this issue. Please review that.

**Comment by TomasVotruba** [comment]
Thanks :+1: 

Resolved by https://github.com/TomasVotruba/tomasvotruba.com/pull/1302
