### ISSUE TITLE
Broken URLs in RSS Feed

### ISSUE THREAD

**Issue by vintagesucks** [TomasVotruba/tomasvotruba.com#1313]
Hi! The URLs in your [RSS feed](https://tomasvotruba.com/rss.xml) are broken and look like this:

* `%env(SITE_URL)/rss.xml`
* `%env(SITE_URL)/blog/how-to-make-configs-like-rector-config-or-ecs-config-for-your-symfony-project`

Probably caused by the changes in #1308?

**Comment by TomasVotruba** [comment]
Hi @vintagesucks ,

thank you for super fast report. You're right, I mixed the env syntax.

This should help: https://github.com/TomasVotruba/tomasvotruba.com/commit/35abb37a3209138b83cad08812ed5ac535e2c909
