### ISSUE TITLE
[post] kernel with diffrent configs, not working with reset-password-bundle

### ISSUE THREAD

**Issue by ganti** [TomasVotruba/tomasvotruba.com#1330]
About: [2022-02-07-how-to-create-symfony-kernel-for-tests-with-different-configs.md](https://github.com/TomasVotruba/tomasvotruba.com/blob/main/packages/blog/data/2022/2022-02-07-how-to-create-symfony-kernel-for-tests-with-different-configs.md)

Your solution collides with [reset-password-bundle](https://github.com/SymfonyCasts/reset-password-bundle):
```
The child config "request_password_repository" under "symfonycasts_reset_password" must be configured:
A class that implements ResetPasswordRequestRepositoryInterface - usually your ResetPasswordRequestRepository.
```

 I already wrote an issue [https://github.com/SymfonyCasts/reset-password-bundle](https://github.com/SymfonyCasts/reset-password-bundle/issues/243) on their page instead of here

maybe you have an idea on how to get your elegant solution working with this  bundle.

**Comment by TomasVotruba** [comment]
Hi, this seems like config loading issue. 
The article only uses Symfony components that load configs.

I think there will be some compiler pass, config or extension that needs to be loaded too.
