### ISSUE TITLE
Box project and creator

### ISSUE THREAD

**Issue by harikt** [TomasVotruba/tomasvotruba.com#912]
Hi,

I was reading this post :  https://github.com/TomasVotruba/tomasvotruba.com/blob/master/source/_posts/2019/2019-12-02-how-to-box-symfony-app-to-phar-without-killing-yourself.md

and noticed 

> There are 2 amazing tools maintained and developed by Théo Fidry (thank you!):

I don't know about php-scoper . But the [box-project](https://github.com/box-project/) was created by [Kevin Herrera](https://github.com/kherge) and the current one https://github.com/humbug/box is a fork of it. So I wonder whether the term `developed` suits here or not.

Nothing against anyone. Just thought of mentioning it.

**Comment by TomasVotruba** [comment]
Hi, what do you suggest?

**Comment by harikt** [comment]
Hi @TomasVotruba , 

> There are 2 amazing tools maintained and developed by Théo Fidry (thank you!):

1. May be we can confirm with @Théo Fidry whether he is the actual person who developed it.
2. If he is the actual person, we can close the issue.
3. If not 
a ) we can remove the term `developed` in the sentence.
b ) Add credit to original author Kevin Herrera as the person who developed it.

**Comment by TomasVotruba** [comment]
I had 3 b) in mind. Care to PR?

**Comment by harikt** [comment]
I will try, but I am still confused how to write it. ie why I created an issue.

**Comment by TomasVotruba** [comment]
3 b)

**Comment by TomasVotruba** [comment]
Send PR when ready. Closing as option was answered
